# Site settings
name: Jan Aagaard's Blog
email: jan@aagaard.net
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "https://janaagaard75.github.com"
twitter_username: janaagaard
github_username: janaaagaard75

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed # /feed.xml
  - jekyll-sitemap # /sitemap.xml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
