# Site settings
title: Jan Aagaard's Blog
email: jan@aagaard.net
description: >-
  Jan Aagaard's blog about programming.
baseurl: ""
url: "https://janaagaard75.github.com"
twitter:
  username: janaagaard
twitter_username: janaagaard
author:
  twitter: janaagaard
github_username: janaaagaard75

# Build settings
kramdown:
  syntax_highlighting: rouge
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
plugins:
  - jekyll-feed # /feed.xml
  - jekyll-seo-tag
  - jekyll-sitemap # /sitemap.xml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
